'use strict';
const $=id=>document.getElementById(id),HOME='https://erwinblom.github.io/werkplaats/Apps/Bronnenkast/Start%20Bronnenkast.html?werkruimte=eigen';
async function request(type,extra={}){const r=await chrome.runtime.sendMessage({type,...extra});if(!r?.ok)throw Error(r?.error||'Geen antwoord. Probeer opnieuw.');return r}
async function status(){const r=await request('status');$('count').textContent=`${r.pending} klaar voor Verzamelen · ${r.total} lokaal bewaard`;}
function error(e){$('message').textContent=e.message}
(async()=>{await status();const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!/^https?:\/\//.test(tab?.url||'')){ $('message').textContent='Open een webpagina of plak hieronder zelf een link.';return;}$('title').value=(tab.title||'').slice(0,180);$('url').value=tab.url;try{const result=await chrome.scripting.executeScript({target:{tabId:tab.id},func:()=>window.getSelection()?.toString()||''});$('quote').value=(result[0]?.result||'').slice(0,10000)}catch{$('message').textContent='Geselecteerde tekst kon niet worden gelezen. Je kunt zelf een citaat plakken.'}})().catch(error);
$('capture').onsubmit=async event=>{event.preventDefault();$('save').disabled=true;try{await request('add',{item:{title:$('title').value,url:$('url').value,quote:$('quote').value,notes:$('notes').value}});$('message').textContent='Lokaal bewaard. Je link wacht op ontvangst in Verzamelen.';await status();}catch(e){error(e);$('save').disabled=false;}};
$('capture').addEventListener('input',()=>$('save').disabled=false);
$('open').onclick=()=>chrome.tabs.create({url:HOME});
$('export').onclick=async()=>{try{const r=await request('export'),u=URL.createObjectURL(new Blob([JSON.stringify(r.data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='gereedschapskist-verzamelen-link-bewaren-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);$('message').textContent='Download gestart. Controleer of je herstelbestand is opgeslagen.';}catch(e){error(e)}};
$('retry').onclick=async()=>{if(!confirm('Alle lokaal bewaarde links opnieuw aanbieden? Bestaande broncodes worden niet dubbel toegevoegd. Verwijderde links kunnen terugkomen.'))return;try{await request('retry');await status();$('message').textContent='Open Verzamelen en klik op Ontvang links.';}catch(e){error(e)}};
