'use strict';
window.Kladblok=(()=>{
 const marker=/\n*<!-- gk-kladblok:v1:([A-Za-z0-9%_.!~*'()-]*) -->\s*$/;
 let note='',opened=false;
 function split(text){const match=String(text).match(marker);if(!match)return {text,note:''};try{return {text:text.slice(0,match.index),note:JSON.parse(decodeURIComponent(match[1]))};}catch{return {text,note:''};}}
 function strip(text){return split(text).text;}
 function pack(text,value){text=strip(text);return value?text.replace(/\n*$/,'')+'\n\n<!-- gk-kladblok:v1:'+encodeURIComponent(JSON.stringify(value)).replace(/-/g,'%2D')+' -->\n':text;}
 function load(text){note=split(text).note;render();}
 function render(){
  document.getElementById('kladblok-panel')?.remove();
  document.body.classList.toggle('kladblok-open',opened&&!!activeFile);
  if(!opened||!activeFile)return;
  const panel=document.createElement('aside');panel.id='kladblok-panel';I18n.attribute(panel,'aria-label',I18n.ui("Kladblok bij dit document",'Kladblok bij dit document'));
  panel.innerHTML="<div class=\"kladblok-heading\"><h2><span data-i18n=\"Kladblok\">Kladblok</span></h2><button type=\"button\" aria-label=\"Sluit kladblok\" data-i18n-aria-label=\"Sluit kladblok\"><span data-i18n=\"Sluit\">Sluit</span></button></div><p class=\"kladblok-name\"></p><p><span data-i18n=\"Bewaar hier ideeën en tekst die je misschien later wilt gebruiken. Dit gaat mee bij bewaren, maar niet bij export. Deel via Exporteren als je alleen de hoofdtekst wilt delen.\">Bewaar hier ideeën en tekst die je misschien later wilt gebruiken. Dit gaat mee bij bewaren, maar niet bij export. Deel via Exporteren als je alleen de hoofdtekst wilt delen.</span></p><label for=\"kladblok-text\"><span data-i18n=\"Notities en tekstfragmenten\">Notities en tekstfragmenten</span></label><textarea id=\"kladblok-text\" placeholder=\"Plak of schrijf hier je notities…\" data-i18n-placeholder=\"Plak of schrijf hier je notities…\"></textarea><div class=\"kladblok-actions\"><button type=\"button\" data-make-note><span data-i18n=\"Maak notitie\">Maak notitie</span></button></div><p class=\"kladblok-status\" role=\"status\"></p>";
  panel.querySelector('.kladblok-name').textContent=activeFile.name;
  const input=panel.querySelector('textarea');input.value=note;input.readOnly=!isEditMode;
  I18n.assign(panel.querySelector('.kladblok-status'),(isEditMode?I18n.ui("Gebruik Bewaar om tekst en kladblok samen te bewaren.",'Gebruik Bewaar om tekst en kladblok samen te bewaren.'):I18n.ui("Kies Bewerk om het kladblok aan te passen.",'Kies Bewerk om het kladblok aan te passen.')),"textContent");
  input.oninput=()=>{note=input.value;wysiwygDirty=true;updateWysiwygModifiedState();window.Werkstatus?.changed();makeNote.disabled=!note.trim();};
  panel.querySelector('.kladblok-heading button').onclick=()=>{opened=false;render();};
  const makeNote=panel.querySelector('[data-make-note]');makeNote.disabled=!note.trim();makeNote.onclick=async()=>{makeNote.disabled=true;const status=panel.querySelector('.kladblok-status');try{await SchrijfNotities.createFromKladblok(note,activeFile);note='';input.value='';wysiwygDirty=true;updateWysiwygModifiedState();Werkstatus.changed();I18n.assign(status,I18n.ui('Notitie gemaakt. Bewaar het document en gebruik daarna Bewaar alles.','Notitie gemaakt. Bewaar het document en gebruik daarna Bewaar alles.'));}catch(error){status.textContent=error.message;makeNote.disabled=!note.trim();}};document.body.append(panel);
 }
 function toggle(){opened=!opened;render();}
 const style=document.createElement('style');I18n.assign(style,I18n.ui("#kladblok-panel{position:fixed;right:16px;top:140px;bottom:24px;width:300px;box-sizing:border-box;padding:18px;background:var(--bg-primary,#fff);color:var(--text-primary,#111);border:1px solid #aaa;overflow:auto;z-index:50;font:14px/1.5 Arial}.kladblok-heading{display:flex;align-items:center;justify-content:space-between;gap:8px}.kladblok-heading h2{margin:0;font-size:20px}#kladblok-panel button{padding:6px;border:1px solid #888;background:transparent;color:inherit;cursor:pointer}#kladblok-panel textarea{box-sizing:border-box;width:100%;min-height:40vh;margin-top:8px;padding:10px;resize:vertical;font:15px/1.6 Arial;background:var(--bg-secondary,#fff);color:inherit;border:1px solid #888}.kladblok-name{font-weight:bold;overflow-wrap:anywhere}.kladblok-open .app{margin-right:330px}.kladblok-actions{display:flex;justify-content:flex-end;margin-top:10px}.kladblok-actions button{font-weight:700}.kladblok-status{font-size:12px}@media(max-width:900px){#kladblok-panel{position:static;width:auto;margin:16px}.kladblok-open .app{margin-right:0}}@media print{#kladblok-panel{display:none!important}.kladblok-open .app{margin-right:0}}",'#kladblok-panel{position:fixed;right:16px;top:140px;bottom:24px;width:300px;box-sizing:border-box;padding:18px;background:var(--bg-primary,#fff);color:var(--text-primary,#111);border:1px solid #aaa;overflow:auto;z-index:50;font:14px/1.5 Arial}.kladblok-heading{display:flex;align-items:center;justify-content:space-between;gap:8px}.kladblok-heading h2{margin:0;font-size:20px}#kladblok-panel button{padding:6px;border:1px solid #888;background:transparent;color:inherit;cursor:pointer}#kladblok-panel textarea{box-sizing:border-box;width:100%;min-height:40vh;margin-top:8px;padding:10px;resize:vertical;font:15px/1.6 Arial;background:var(--bg-secondary,#fff);color:inherit;border:1px solid #888}.kladblok-name{font-weight:bold;overflow-wrap:anywhere}.kladblok-open .app{margin-right:330px}.kladblok-actions{display:flex;justify-content:flex-end;margin-top:10px}.kladblok-actions button{font-weight:700}.kladblok-status{font-size:12px}@media(max-width:900px){#kladblok-panel{position:static;width:auto;margin:16px}.kladblok-open .app{margin-right:0}}@media print{#kladblok-panel{display:none!important}.kladblok-open .app{margin-right:0}}'),"textContent");document.head.append(style);
 document.addEventListener('DOMContentLoaded',()=>{
  const content=document.getElementById('content');
  if(content)new MutationObserver(()=>{if(!activeFile&&document.getElementById('kladblok-panel'))render();}).observe(content,{childList:true});
 });
 return {split,strip,pack,load,toggle,render,attach:text=>pack(text,note)};
})();
