'use strict';
(()=>{
 const K=Koppelingen,chosen=new Set();
 document.addEventListener('werkbestand-geopend',()=>{chosen.clear();if(document.getElementById('sources-document'))document.getElementById('sources-document').disabled=true;render()});
 function decorate(){for(const b of $('cards').querySelectorAll('[data-detail]')){const card=b.closest('article');if(card.querySelector('.link-select'))continue;const i=data.items.find(x=>x.id===b.dataset.detail),l=document.createElement('label'),c=document.createElement('input');l.className='link-select';I18n.assign(l,I18n.ui("Selecteer voor document",'Selecteer voor document'),"title");c.type='checkbox';c.checked=chosen.has(i.id);I18n.attribute(c,'aria-label',I18n.ui("Selecteer bron voor document: {0}",'Selecteer bron voor document: '+i.title));c.onchange=()=>{c.checked?chosen.add(i.id):chosen.delete(i.id);document.getElementById('sources-document').disabled=chosen.size===0;};l.append(c);card.querySelector('.card-head').prepend(l);}}
 const oldRender=render;render=function(){oldRender();decorate()};new MutationObserver(decorate).observe($('cards'),{childList:true});decorate();
 const md=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/([\\`*_{}\[\]()#+.!|~-])/g,'\\$1');
 I18n.mark(K.button('Maak document','sources-document',()=>{K.ready();K.fresh();const list=data.items.filter(i=>chosen.has(i.id));if(!list.length)throw Error(I18n.value(I18n.ui("Selecteer eerst bronnen op de kaarten.",'Selecteer eerst bronnen op de kaarten.')));K.dialog('Bronnen naar Schrijven',"<p>"+(list.length)+" <span data-i18n=\"geselecteerde bronnen worden een bewerkbaar Markdown-document, inclusief links, citaten en eigen notities.\">geselecteerde bronnen worden een bewerkbaar Markdown-document, inclusief links, citaten en eigen notities.</span></p><label><span data-i18n=\"Documenttitel\">Documenttitel</span><input name=\"title\" required maxlength=\"180\" value=\""+(K.esc(data.name||'Mijn bronnen'))+"\"></label>",async form=>{K.fresh();const title=K.text(form.elements.title.value.trim(),180,true);let content='# '+md(title)+'\n\n';for(const i of list){content+='## '+md(i.title)+'\n\n';if(i.source)content+='Bron: '+md(i.source)+'\n\n';if(i.url){const url=safeURL(i.url);if(!url)throw Error(I18n.value(I18n.ui("Een bron heeft een ongeldige link.",'Een bron heeft een ongeldige link.')));content+='[Open bron](<'+url.replace(/</g,'%3C').replace(/>/g,'%3E')+'>)\n\n';}if(i.summary)content+=md(i.summary)+'\n\n';if(i.quote)content+='### Citaat\n\n'+md(i.quote).split('\n').map(s=>'> '+s).join('\n')+'\n\n';if(i.notes)content+='### Eigen notities\n\n'+md(i.notes)+'\n\n';}const slug=title.toLocaleLowerCase('nl').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'bronnen';const filename='gereedschapskist-'+(GereedschapskistMode.example?'voorbeeld-':'')+'schrijven-'+slug+'-'+K.today()+'.md';if(!GereedschapskistMode.example&&window.Samenwerken&&window.ProjectMaterials){const savedName=await Samenwerken.document(filename,content);try{await ProjectMaterials.addSourcesToDocument(list.map(i=>i.id),'converter/'+savedName);render();K.notice(I18n.value(I18n.ui("Document {0} aangemaakt in Schrijven en gekoppeld aan de geselecteerde bronnen. Gebruik Bewaar alles.",'Document '+savedName+' aangemaakt in Schrijven en gekoppeld aan de geselecteerde bronnen. Gebruik Bewaar alles.')),'Werkbank');}catch(error){K.notice(I18n.value(I18n.ui("Document {0} is aangemaakt, maar de bronkoppeling is niet bewaard: {1}",'Document '+savedName+' is aangemaakt, maar de bronkoppeling is niet bewaard: '+error.message)),'Werkbank');}}else await K.deliver(new Blob([content],{type:'text/markdown;charset=utf-8'}),filename,'Werkbank','Kies in Schrijven Document openen en selecteer dit Markdown-bestand.');},'Bewaar document');}),"Maak document");
document.getElementById('sources-document').disabled=true;
})();
