'use strict';
window.Koppelingen=(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const uid=()=>crypto.randomUUID(),today=()=>new Date().toLocaleDateString('sv-SE');
 const paths={Ping:'../Ping/Start%20Ping.html',Uren:'../Uren/Start%20Uren.html',Kasboek:'../Kasboek/Start%20Kasboek.html',Projectbord:'../Projectbord/Start%20Projectbord.html',Werkbank:'../Werkbank/%E2%96%B6%20Begin%20hier.html'};
 const names={Ping:'Factureren',Uren:'Uren schrijven',Kasboek:'Boekhouden',Projectbord:'Doen',Werkbank:'Schrijven'};
 const drafts=new Map();let dialogCount=0;
 function text(v,max=200,required=false){if(typeof v!=='string'||v.length>max||required&&!v.trim())throw Error(I18n.value(I18n.ui("Een tekstveld ontbreekt of is te lang.",'Een tekstveld ontbreekt of is te lang.')));return v;}
 function integer(v,min,max){if(!Number.isSafeInteger(v)||v<min||v>max)throw Error(I18n.value(I18n.ui("Een aantal of bedrag is ongeldig.",'Een aantal of bedrag is ongeldig.')));return v;}
 function date(v,required=true){text(v,10,required);if(!v&&!required)return v;if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||v<'1900-01-01'||isNaN(Date.parse(v+'T12:00:00Z'))||new Date(v+'T12:00:00Z').toISOString().slice(0,10)!==v)throw Error(I18n.value(I18n.ui("Een datum is ongeldig.",'Een datum is ongeldig.')));return v;}
 function id(v){return text(v,100,true)}
 function rate(v){if(v===''||v===null||v===undefined)return null;const s=String(v).trim().replace(',','.');if(!/^\d{1,7}(\.\d{1,2})?$/.test(s))throw Error(I18n.value(I18n.ui("Vul een uurtarief in met maximaal twee decimalen.",'Vul een uurtarief in met maximaal twee decimalen.')));return integer(Math.round(Number(s)*100),0,100000000);}
 function vat(v){if(![0,9,21].includes(v))throw Error(I18n.value(I18n.ui("Ongeldig btw-percentage.",'Ongeldig btw-percentage.')));return v;}
 function number(v){text(v,32,true);if(!/^(?:[A-Z0-9]{1,16}-)?\d{4}-\d{3,6}$/.test(v))throw Error(I18n.value(I18n.ui("Ongeldig definitief factuurnummer.",'Ongeldig definitief factuurnummer.')));return v;}
 function digest(v){text(v,64,true);if(!/^[a-f0-9]{64}$/.test(v))throw Error(I18n.value(I18n.ui("Ongeldige bronverwijzing.",'Ongeldige bronverwijzing.')));return v;}
 async function key(parts){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(parts))))].map(n=>n.toString(16).padStart(2,'0')).join('');}
 const signature=i=>key([i.date,i.client,i.project,i.description,i.minutes,i.rateCents,i.vat??21]);
 const euro=c=>new Intl.NumberFormat(I18n.locale(),{style:'currency',currency:'EUR'}).format(c/100);
 const duration=n=>Math.floor(n/60)+':'+String(n%60).padStart(2,'0');
 function timeFields(i={}){const out={};for(const k of ['contactId','projectId'])if(i[k])out[k]=id(i[k]);if(i.rateCents!==undefined)out.rateCents=i.rateCents===null?null:integer(i.rateCents,0,100000000);if(i.vat!==undefined)out.vat=vat(i.vat);
  for(const k of ['sourceTaskId','sourceTransferId'])if(i[k]!==undefined)out[k]=id(i[k]);
  if(i.billing!==undefined){const b=i.billing;if(!b||!['prepared','invoiced'].includes(b.status))throw Error(I18n.value(I18n.ui("Ongeldige factuurstatus bij uren.",'Ongeldige factuurstatus bij uren.')));out.billing={batchId:id(b.batchId),status:b.status,signature:digest(b.signature)};if(b.status==='invoiced'){out.billing.invoiceId=id(b.invoiceId);out.billing.number=number(b.number);}}
  return out;
 }
 function cashFields(i){const out={};for(const k of ['sourceInvoiceId','sourceInvoiceNumber','sourceInvoiceKey','sourcePaymentId','projectId'])if(i[k]!==undefined&&(k!=='projectId'||i[k]))out[k]=k==='sourceInvoiceNumber'?number(i[k]):k==='sourceInvoiceKey'?digest(i[k]):id(i[k]);return out;}
 function taskFields(i){const out={};if(['inbox','todo','doing'].includes(i.previousState))out.previousState=i.previousState;for(const k of ['contactId','projectId'])if(i[k])out[k]=id(i[k]);if(i.project!==undefined)out.project=text(i.project,200);if(i.sourceLink!==undefined)out.sourceLink=digest(i.sourceLink);return out;}
 function source(i){if(!i||typeof i!=='object')throw Error(I18n.value(I18n.ui("Ongeldige urenbron.",'Ongeldige urenbron.')));return {id:id(i.id),batchId:id(i.batchId),signature:digest(i.signature),date:date(i.date),client:text(i.client,200,true),project:text(i.project,200,true),description:text(i.description,2000,true),minutes:integer(i.minutes,1,1440),rateCents:integer(i.rateCents,1,100000000),vat:vat(i.vat),...(i.projectId?{projectId:id(i.projectId)}:{}),...(i.contactId?{contactId:id(i.contactId)}:{})};}
 function sources(list){if(!Array.isArray(list)||!list.length||list.length>100)throw Error(I18n.value(I18n.ui("Kies 1 tot 100 registraties.",'Kies 1 tot 100 registraties.')));const ids=new Set();return list.map(i=>{const s=source(i);if(ids.has(s.id))throw Error(I18n.value(I18n.ui("Dubbele urenregistratie.",'Dubbele urenregistratie.')));ids.add(s.id);return s;});}
 function invoiceFields(i){if(i.timeSources===undefined)return;const list=sources(i.timeSources),linked=i.lines.filter(l=>l.hourSourceId!==undefined);if(!linked.length&&!i.sourceQuoteId&&i.lines.length===list.length)return;const ids=new Set(list.map(s=>s.id)),seen=new Set();for(const l of linked){id(l.hourSourceId);if(!ids.has(l.hourSourceId)||seen.has(l.hourSourceId))throw Error(I18n.value(I18n.ui("Een urenregel heeft geen unieke bron.",'Een urenregel heeft geen unieke bron.')));seen.add(l.hourSourceId);}if(seen.size!==ids.size)throw Error(I18n.value(I18n.ui("Niet alle overgenomen uren staan op de factuur.",'Niet alle overgenomen uren staan op de factuur.')));}
 function appendHours(invoice,list){if(invoice.state!=='draft')throw Error(I18n.value(I18n.ui("Alleen een conceptfactuur kan uren ontvangen.",'Alleen een conceptfactuur kan uren ontvangen.')));const incoming=sources(list),known=new Set((invoice.timeSources||[]).map(s=>s.id));if(incoming.some(s=>known.has(s.id)))throw Error(I18n.value(I18n.ui("Deze uren staan al op deze factuur.",'Deze uren staan al op deze factuur.')));if(incoming.some(s=>s.client.trim().toLocaleLowerCase('nl')!==invoice.customer.trim().toLocaleLowerCase('nl')||invoice.projectId&&s.projectId!==invoice.projectId||invoice.sourceContactId&&s.contactId&&s.contactId!==invoice.sourceContactId))throw Error(I18n.value(I18n.ui("Klant of project van de uren past niet bij de factuur.",'Klant of project van de uren past niet bij de factuur.')));if(invoice.timeSources&&!invoice.lines.some(l=>l.hourSourceId))invoice.lines.forEach((l,n)=>l.hourSourceId=invoice.timeSources[n].id);invoice.timeSources=[...(invoice.timeSources||[]),...incoming];invoice.lines.push(...incoming.map(s=>({hourSourceId:s.id,description:s.date+' · '+s.project+' · '+s.description+' ('+duration(s.minutes)+' uur × '+euro(s.rateCents)+'/uur)',quantity:1,cents:Math.round(s.minutes*s.rateCents/60),vat:s.vat})));if(!invoice.deliveryDate)invoice.deliveryDate=incoming.map(s=>s.date).sort().at(-1);if(!invoice.projectId&&new Set(incoming.map(s=>s.projectId||'')).size===1)invoice.projectId=incoming[0].projectId||'';if(!invoice.sourceContactId&&new Set(incoming.map(s=>s.contactId||'')).size===1)invoice.sourceContactId=incoming[0].contactId||'';invoiceFields(invoice);return invoice;}
 function invoiceBalance(invoice,entries){const linked=entries.filter(e=>e.sourceInvoiceId===invoice.sourceInvoiceId||e.sourceInvoiceKey&&e.sourceInvoiceKey===invoice.sourceInvoiceKey);const received=linked.reduce((sum,e)=>sum+(e.type==='income'?e.cents:-e.cents),0);return {received,remaining:Math.max(0,invoice.cents-received),overpaid:Math.max(0,received-invoice.cents),payments:linked.length};}
 function envelope(p,kinds){if(!p||p.format!=='gereedschapskist-overdracht'||p.version!==1||!kinds.includes(p.kind))throw Error(I18n.value(I18n.ui("Kies het juiste overdrachtsbestand voor deze knop.",'Kies het juiste overdrachtsbestand voor deze knop.')));id(p.id);if(Boolean(p._gereedschapskistExample)!==GereedschapskistMode.example)throw Error(I18n.value(I18n.ui("Open dit bestand in dezelfde werkruimte: eigen werk of voorbeelden.",'Open dit bestand in dezelfde werkruimte: eigen werk of voorbeelden.')));return p;}
 function ready(){if(Werkstatus.hasPending())throw Error(I18n.value(I18n.ui("Bewaar of sluit eerst het gewijzigde formulier.",'Bewaar of sluit eerst het gewijzigde formulier.')));}
 function fresh(){let raw;try{raw=GereedschapskistMode.storage.getItem(KEY)}catch{return}if(raw!==lastRaw)throw Error(I18n.value(I18n.ui("Deze tool is in een ander venster gewijzigd. Herlaad eerst.",'Deze tool is in een ander venster gewijzigd. Herlaad eerst.')));}
 function notice(message,destination){let box=document.getElementById('link-result');if(!box){box=document.createElement('section');box.id='link-result';box.className='link-result';box.setAttribute('role','status');document.querySelector('main').prepend(box);}box.replaceChildren();const p=document.createElement('p');p.textContent=message;box.append(p);if(destination){const a=document.createElement('a');a.href=paths[destination]+'?werkruimte='+(GereedschapskistMode.example?'voorbeeld':'eigen');I18n.assign(a,I18n.ui("Open {0}",'Open '+I18n.t(names[destination])),"textContent");a.className='transfer-open';box.append(a);}return box;}
 async function deliver(blob,name,destination,instruction){if(destination==='Werkbank'&&window.Samenwerken&&!GereedschapskistMode.example){const savedName=await Samenwerken.document(name,await blob.text());notice(I18n.value(I18n.ui("Document {0} aangemaakt in Schrijven met een kopie van de geselecteerde bronnen. De bronnen blijven behouden. Gebruik Bewaar alles om je werk vast te leggen.",'Document '+savedName+' aangemaakt in Schrijven met een kopie van de geselecteerde bronnen. De bronnen blijven behouden. Gebruik Bewaar alles om je werk vast te leggen.')),destination);return true;}await Werkmap.ready;if(Werkmap.active){if(!await Werkmap.exportFile(blob,name))throw Error(I18n.value(I18n.ui("Overdracht niet bewaard. Controleer de werkmapmelding en probeer opnieuw.",'Overdracht niet bewaard. Controleer de werkmapmelding en probeer opnieuw.')));notice(I18n.value(I18n.ui("Bestand bewaard in Exports bij deze tool. {0}",'Bestand bewaard in Exports bij deze tool. '+instruction)),destination);}else{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);notice(I18n.value(I18n.ui("Download gestart. Controleer of het bestand is opgeslagen. {0}",'Download gestart. Controleer of het bestand is opgeslagen. '+instruction)),destination);}return true;}
 async function send(kind,body,destination,instruction,transferId=uid()){
  if(window.Samenwerken&&(!GereedschapskistMode.example||kind==='taken'||kind==='offerte-factuur')){const result=await Samenwerken.send(kind,body,destination,transferId);notice(I18n.value(I18n.ui("{0} Gebruik Bewaar alles om je werk vast te leggen.",result.message+' Gebruik Bewaar alles om je werk vast te leggen.')),destination);return true;}
  const payload=GereedschapskistMode.forExport({format:'gereedschapskist-overdracht',version:1,id:transferId,kind,body});
  const stamp=new Date().toISOString().replace(/[:.]/g,'-');const name='gereedschapskist-'+(GereedschapskistMode.example?'voorbeeld-':'')+kind+'-'+stamp+'.json';
  return deliver(new Blob([JSON.stringify(payload,null,2)+'\n'],{type:'application/json'}),name,destination,instruction);
 }
 function actions(){let bar=document.getElementById('link-actions');if(!bar){bar=document.createElement('div');bar.id='link-actions';bar.className='link-actions';document.querySelector('main').prepend(bar);}return bar;}
 function button(label,id,onClick){const b=document.createElement('button');b.type='button';b.id=id;I18n.assign(b,I18n.ui(label,label));b.onclick=async()=>{try{await onClick()}catch(e){notice(e.message)}};actions().append(b);return b;}
 function receiver(label,id,kinds,receive){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.hidden=true;input.id=id+'-file';document.body.append(input);button(label,id,()=>{ready();input.click()});input.onchange=async()=>{const file=input.files[0];input.value='';if(!file)return;try{if(file.size>2000000)throw Error(I18n.value(I18n.ui("Maximaal 2 MB per overdracht.",'Maximaal 2 MB per overdracht.')));ready();const p=envelope(JSON.parse(await file.text()),kinds);fresh();await receive(p);}catch(e){notice(I18n.value(I18n.ui("Niet overgenomen: {0}",'Niet overgenomen: '+e.message)))}};}
 function dialog(title,html,submit,label='Overnemen'){
  const heading=title;title=I18n.value(title);
  const d=document.createElement('dialog');d.className='link-dialog';d.id='link-dialog-'+(++dialogCount);d.setAttribute('aria-labelledby',d.id+'-title');d.innerHTML="<form><h2 id=\""+(d.id)+"-title\">"+(esc(title))+"</h2>"+(html)+"<p class=\"link-error\" role=\"status\"></p><div class=\"link-actions wp-actions\"><button type=\"button\" data-cancel><span data-i18n=\"Annuleer\">Annuleer</span></button><button class=\"primary action-primary\" type=\"submit\">"+(esc(label))+"</button></div></form>";document.body.append(d);I18n.assign(d.querySelector('h2'),typeof heading==='object'?heading:I18n.ui(heading,heading));I18n.assign(d.querySelector('button:not([type=button])'),I18n.ui(label,label));const form=d.querySelector('form');let busy=false;
  const snapshot=()=>JSON.stringify([...form.querySelectorAll('input,textarea,select')].map(x=>[x.value,x.checked]));let baseline='';
  const close=()=>{if(busy)return;if(snapshot()!==baseline&&!confirm(I18n.value(I18n.ui("Je hebt onbewaarde invoer. Wil je die weggooien?",'Je hebt onbewaarde invoer. Wil je die weggooien?'))))return;d.close()};d.querySelector('[data-cancel]').onclick=close;d.oncancel=e=>{e.preventDefault();close()};d.onclose=()=>d.remove();
  form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const b=form.querySelector('[type=submit]');b.disabled=true;try{const result=await submit(form,d);if(result!==false)d.close();}catch(err){form.querySelector('.link-error').textContent=err.message;}finally{busy=false;b.disabled=false;}};
  const unload=e=>{if(d.open&&(busy||snapshot()!==baseline)){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',unload);d.addEventListener('close',()=>window.removeEventListener('beforeunload',unload));d.showModal();baseline=snapshot();return {dialog:d,form,resetBaseline:()=>baseline=snapshot()};
 }
 document.addEventListener('DOMContentLoaded',()=>{const style=document.createElement('style');I18n.assign(style,I18n.ui(".link-actions{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.link-result{border-left:4px solid var(--wp-accent,#e32720);padding:12px 16px;margin:14px 0;background:#f4f4f4;font:14px/1.5 Arial;color:#111}.link-result p{margin:0 0 6px}.link-result a{font-weight:bold}.link-dialog label{display:block;margin:10px 0}.link-dialog input:not([type=checkbox]),.link-dialog textarea,.link-dialog select{width:100%;padding:8px;border:1px solid #999;font:inherit;box-sizing:border-box}.link-dialog input[type=checkbox],.link-select input{width:20px!important;height:20px;vertical-align:middle}.link-dialog .link-row{border-top:1px solid #bbb;padding:12px 0}.link-dialog .link-error{color:#b21b15}.link-select{display:inline-flex!important;align-items:center;gap:8px;font:13px Arial;margin:8px 0}.link-billing{font-size:12px;color:#595959;margin:8px 0}.link-dialog button:focus-visible,.link-dialog input:focus-visible,.link-dialog textarea:focus-visible,.link-actions button:focus-visible{outline:3px solid var(--wp-accent,#e32720);outline-offset:3px}@media print{.link-actions,.link-result,.link-dialog,.link-select,.link-billing{display:none!important}}",'.link-actions{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.link-result{border-left:4px solid var(--wp-accent,#e32720);padding:12px 16px;margin:14px 0;background:#f4f4f4;font:14px/1.5 Arial;color:#111}.link-result p{margin:0 0 6px}.link-result a{font-weight:bold}.link-dialog label{display:block;margin:10px 0}.link-dialog input:not([type=checkbox]),.link-dialog textarea,.link-dialog select{width:100%;padding:8px;border:1px solid #999;font:inherit;box-sizing:border-box}.link-dialog input[type=checkbox],.link-select input{width:20px!important;height:20px;vertical-align:middle}.link-dialog .link-row{border-top:1px solid #bbb;padding:12px 0}.link-dialog .link-error{color:#b21b15}.link-select{display:inline-flex!important;align-items:center;gap:8px;font:13px Arial;margin:8px 0}.link-billing{font-size:12px;color:#595959;margin:8px 0}.link-dialog button:focus-visible,.link-dialog input:focus-visible,.link-dialog textarea:focus-visible,.link-actions button:focus-visible{outline:3px solid var(--wp-accent,#e32720);outline-offset:3px}@media print{.link-actions,.link-result,.link-dialog,.link-select,.link-billing{display:none!important}}'),"textContent");document.head.append(style);});
 return {esc,uid,today,text,id,integer,date,rate,vat,number,key,digest,signature,euro,duration,timeFields,cashFields,taskFields,sources,invoiceFields,appendHours,invoiceBalance,ready,fresh,notice,send,deliver,button,receiver,dialog,draft:k=>drafts.get(k)||{},setDraft:(k,v)=>drafts.set(k,v)};
})();
