'use strict';
(()=>{
 const K=Koppelingen,oldEdit=edit;edit=function(id=null,preserveDraft=false){if(!preserveDraft)K.setDraft('Kasboek',{});oldEdit(id)};
 const duplicate=b=>b.sourcePaymentId&&data.entries.some(i=>i.id!==editing&&i.sourcePaymentId===b.sourcePaymentId);
 const submit=$('form').onsubmit;$('form').onsubmit=e=>{const b=K.draft('Kasboek');if(duplicate(b)){e.preventDefault();notify(I18n.value(I18n.ui("Deze betaling is al overgenomen. Er is niets toegevoegd.",'Deze betaling is al overgenomen. Er is niets toegevoegd.')));return;}submit(e)};
 K.receiver('Factuur overnemen','take-invoice',['factuur-boekhouding'],async p=>{const i=p.body?.invoice,credit=i?.kind==='credit';K.id(i?.id);K.number(i.number);K.date(i.date);K.date(i.due||'',false);K.text(i.customer,200,true);K.text(i.title,2000,true);K.integer(i.cents,credit?-100000000:1,credit?-1:100000000);K.integer(i.netCents,credit?-100000000:0,credit?0:100000000);K.integer(i.vatCents,credit?-100000000:0,credit?0:100000000);if(i.netCents+i.vatCents!==i.cents)throw Error(I18n.value(I18n.ui("Factuurbedragen sluiten niet op elkaar aan.",'Factuurbedragen sluiten niet op elkaar aan.')));if(credit)K.number(i.creditFor);for(const field of ['name','kvk','vat'])K.text(i.issuer?.[field],4000,field==='name');const sourceInvoiceKey=await K.key([i.issuer.kvk.trim().toLowerCase()||i.issuer.vat.trim().toLowerCase()||i.issuer.name.trim().toLowerCase(),i.number]);const record=validateLinkedInvoice({sourceInvoiceId:i.id,sourceInvoiceKey,projectId:i.projectId||'',kind:credit?'credit':'invoice',creditFor:credit?i.creditFor:'',number:i.number,date:i.date,due:i.due||'',customer:i.customer,title:i.title,cents:i.cents,netCents:i.netCents,vatCents:i.vatCents,vatLines:i.vatLines,vatMode:i.vatMode});K.fresh();if((data.invoices||[]).some(old=>old.sourceInvoiceId===record.sourceInvoiceId||old.sourceInvoiceKey===record.sourceInvoiceKey))throw Error(I18n.value(I18n.ui("Deze factuur staat al in Boekhouden.",'Deze factuur staat al in Boekhouden.')));if(credit){const original=data.invoices.find(old=>old.kind==='invoice'&&old.number===record.creditFor);if(!original)throw Error(I18n.value(I18n.ui("Neem eerst de oorspronkelijke factuur over.",'Neem eerst de oorspronkelijke factuur over.')));}if(change(d=>{d.invoices=d.invoices||[];d.invoices.unshift(record)}))K.notice(I18n.value(I18n.ui("{0} toegevoegd aan het factuuroverzicht. Betalingen blijven aparte boekingen. Gebruik Bewaar alles voor je werkmap.",(credit?'Creditfactuur':'Factuur')+' toegevoegd aan het factuuroverzicht. Betalingen blijven aparte boekingen. Gebruik Bewaar alles voor je werkmap.')));});

 K.receiver('Ontvangst overnemen','take-receipt',['factuur-ontvangst'],async p=>{const b=p.body;K.id(b?.invoiceId);K.number(b.number);K.text(b.customer,200,true);K.integer(b.cents,1,100000000);K.date(b.receivedOn);for(const field of ['name','kvk','vat'])K.text(b.issuer?.[field],4000,field==='name');const meta={projectId:b.projectId||'',sourceInvoiceId:b.invoiceId,sourceInvoiceNumber:b.number,sourcePaymentId:K.id(b.paymentId||p.id),sourceInvoiceKey:await K.key([b.issuer.kvk.trim().toLowerCase()||b.issuer.vat.trim().toLowerCase()||b.issuer.name.trim().toLowerCase(),b.number])};editing=null;K.fresh();if(duplicate(meta))throw Error(I18n.value(I18n.ui("Deze betaling is al overgenomen.",'Deze betaling is al overgenomen.')));const invoice=data.invoices.find(i=>i.sourceInvoiceId===meta.sourceInvoiceId&&i.sourceInvoiceKey===meta.sourceInvoiceKey);if(!invoice)throw Error(I18n.value(I18n.ui("Neem deze factuur eerst over in Boekhouden.",'Neem deze factuur eerst over in Boekhouden.')));if(invoice.kind==='credit'||invoice.customer!==b.customer||invoice.projectId!==(b.projectId||''))throw Error(I18n.value(I18n.ui("Betaling past niet bij deze factuur.",'Betaling past niet bij deze factuur.')));if(data.invoices.some(c=>c.kind==='credit'&&c.creditFor===invoice.number))throw Error(I18n.value(I18n.ui("Deze factuur is gecrediteerd; boek zo nodig een terugbetaling.",'Deze factuur is gecrediteerd; boek zo nodig een terugbetaling.')));if(b.cents>K.invoiceBalance(invoice,data.entries).remaining)throw Error(I18n.value(I18n.ui("De betaling is hoger dan het openstaande bedrag.",'De betaling is hoger dan het openstaande bedrag.')));K.setDraft('Kasboek',meta);edit(null,true);$('date').value=b.receivedOn;$('type').value='income';$('party').value=b.customer;$('description').value='Ontvangen factuur '+b.number;$('category').value='Omzet';$('amount').value=(b.cents/100).toFixed(2).replace('.',',');I18n.assign($('form-title'),I18n.ui("Ontvangst controleren · {0}",'Ontvangst controleren · '+b.number),"textContent");K.notice(I18n.value(I18n.ui("Controleer de betaling en bewaar de boeking. Bewaar daarna je boekhoudbestand.",'Controleer de betaling en bewaar de boeking. Bewaar daarna je boekhoudbestand.')));});
})();
